/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Browse": {                                      "nds": "Durchsuchen",                                     "en": "Browse",                                          "de": "Durchsuchen",                                     "ru": "Просматривать",                                   "pt": "procurar",                                        "nl": "Blader",                                          "fr": "Feuilleter",                                      "it": "Navigare",                                        "es": "Vistazo",                                         "pl": "Paść się",                                        "zh-cn": "浏览"},
    "MAX! CUL adapter settings": {                   "nds": "MAX! CUL Adapter Einstellungen",                  "en": "MAX! CUL adapter settings",                       "de": "MAX! CUL-Adaptereinstellungen",                   "ru": "Настройки MAX! CUL Драйвера",                     "pt": "Configurações do adaptador MAX! CUL",             "nl": "MAX! CUL adapter settings",                       "fr": "MAX! CUL adapter settings",                       "it": "MAX! CUL adapter settings",                       "es": "MAX! CUL adapter settings",                       "pl": "MAX! CUL adapter settings",                       "zh-cn": "最大限度！ "},
    "MAX! Cube IP:": {                               "nds": "MAX! Cube IP",                                    "en": "MAX! Cube IP",                                    "de": "MAX! Cube IP",                                    "ru": "MAX! Cube IP",                                    "pt": "MAX! Cube IP",                                    "nl": "MAX! Cube IP",                                    "fr": "MAX! Cube IP",                                    "it": "MAX! Cube IP",                                    "es": "MAX! Cube IP",                                    "pl": "MAX! Cube IP",                                    "zh-cn": "最大限度！"},
    "MAX! Cube Port:": {                             "nds": "MAX! Cube Port",                                  "en": "MAX! Cube Port",                                  "de": "MAX! Cube Port",                                  "ru": "MAX! Cube Port",                                  "pt": "MAX! Cube Porta",                                 "nl": "MAX! Cube Port",                                  "fr": "MAX! Cube Port",                                  "it": "MAX! Cube Port",                                  "es": "MAX! Cube Port",                                  "pl": "MAX! Cube Port",                                  "zh-cn": "最大限度！"},
    "Own IP interface:": {                           "nds": "Eigene IP Schnittstelle",                         "en": "Own IP interface",                                "de": "Eigene IP-Schnittstelle",                         "ru": "Собственный IP-интерфейс",                        "pt": "Própria Interface IP",                            "nl": "Eigen IP-interface",                              "fr": "Propre interface IP",                             "it": "Proprio interfaccia IP",                          "es": "Interfaz IP propia",                              "pl": "Własny interfejs IP",                             "zh-cn": "自己的IP接口"},
    "Refresh interval (ms):": {                      "nds": "Auffrischungsintervall (ms)",                     "en": "Refresh interval (ms)",                           "de": "Aktualisierungsintervall (ms)",                   "ru": "Интервал обновления (мс)",                        "pt": "Intervalo de atualização (ms)",                   "nl": "Interval vernieuwen (ms)",                        "fr": "Intervalle d'actualisation (ms)",                 "it": "Intervallo di aggiornamento (ms)",                "es": "Intervalo de actualización (ms)",                 "pl": "Interwał odświeżania (ms)",                       "zh-cn": "刷新间隔（毫秒）"},
    "Reconnect interval (ms):": {                    "nds": "Neuverbindungsintervall (ms)",                    "en": "Reconnect interval (ms)",                         "de": "Verbindungsintervall (ms)",                       "ru": "Интервал повторного подключения (мс)",            "pt": "Intervalo de reconexão (ms)",                     "nl": "Reconnect interval (ms)",                         "fr": "Intervalle de reconnexion (ms)",                  "it": "Intervallo di riconnessione (ms)",                "es": "Intervalo de reconexión (ms)",                    "pl": "Interwał ponownego połączenia (ms)",              "zh-cn": "重新连接间隔（毫秒）"},
    "Listen on all IPs": {                           "nds": "Anfragen für alle IPs beantworten",               "en": "Listen on all IPs",                               "de": "Anfragen für alle IPs beantworten",               "ru": "Ожидать соединения на всех IP адресах",           "pt": "Ouça em todos os IPs",                            "nl": "Luister op alle IP's",                            "fr": "Écoutez sur toutes les adresses IP",              "it": "Ascolta su tutti gli IP",                         "es": "Escuchar en todas las direcciones IP",            "pl": "Posłuchaj na wszystkich IP",                      "zh-cn": "聆听所有IP"},
    "Find Bridge": {                                 "nds": "Suche Bridge",                                    "en": "Find Bridge",                                     "de": "Suche die Bridge",                                "ru": "Find Bridge",                                     "pt": "Procurar Bridge",                                 "nl": "Find Bridge",                                     "fr": "Find Bridge",                                     "it": "Find Bridge",                                     "es": "Find Bridge",                                     "pl": "Find Bridge",                                     "zh-cn": "寻找桥梁"},
};